/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  CCRL_RL78_G14                          */
/*      FILE         :  CCRL_RL78_G14.c                        */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G14                             */
/*      CPU TYPE     :  R5F104PJ                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              
                                                                           
                                                                           
                                                                           
                                                                          
/***********************************************************************/
/*                                                                     */
/*  FILE        :Main.c                                                */
/*  DATE        :                                                      */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :                                                      */
/*                                                                     */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

void main(void);

void main(void)
{

}
